[package]
name = "bad-apple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
image = "0.25.1"
rodio = "0.18.1"
ffmpeg-next = "7.0.1"
