name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install FFmpeg and ALSA system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libavutil-dev \
          libavcodec-dev \
          libavformat-dev \
          libavdevice-dev \
          libavfilter-dev \
          libswscale-dev \
          libasound2-dev \
          pkg-config

    - name: Build release binary
      run: cargo build --release

    - name: Package binary
      run: |
        mkdir -p dist
        cp target/release/bad-apple dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bad-apple-terminal-release
        path: dist/bad-apple
